name: example
on:
  workflow_dispatch:  # 手动触发
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 211290
          schedule-id: 100001
          seat-id: 1_0
          #slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}  # 确保这里正确引用了 Secret
          message: 'Ticket is available! Hurry up and check: https://www.melon-ticket.com'

      - name: Send Email Notification
        if: success()  # 只有检查成功时发送邮件
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.163.com  # 网易邮箱的SMTP服务器
          server_port: 465  # 网易邮箱的SMTP端口
          username: ${{ secrets.NETEASE_EMAIL_USER }}  # 引用 Secrets
          password: ${{ secrets.NETEASE_EMAIL_PASSWORD }}  # 引用 Secrets
          subject: Ticket Availability Notification
          body: ${{ steps.check-tickets.outputs.message }}  # 获取上一步的输出
          to: ${{ secrets.EMAIL_RECIPIENT }}
          from: ${{ secrets.NETEASE_EMAIL_USER }}
          secure: true
